src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Direct_Link__c</fullName>
        <description>Direct link for registration</description>
        <label>Direct Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>External_Client_String__c</fullName>
        <externalId>true</externalId>
        <label>External Client String</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AccountTriggerHandler.cls
public class AccountTriggerHandler {
	
	public static void beforeUpsert(Account[] accs, Map<Id, Account> oldAccmap) {
		for(account a : accs){

			if(a.Direct_Link__c != null &&
				(trigger.isInsert || (trigger.isUpdate && a.Direct_Link__c != oldAccmap.get(a.id).Direct_Link__c))){
				
				String[] sss = a.Direct_Link__c.split('/');
				
				integer siz = sss.size()-1;

				string ss = sss[siz];
				
				if(ss == 'register'){
					integer i = siz-1;
					a.External_Client_String__c = sss[i];
				}
				else{
					a.External_Client_String__c = 'Bad Direct Registration URL';
				}
			}
		}
	}
}