src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Entity</label>
        <referenceTo>Partner__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sales_Channel__c.object
<CustomObject>
    <fields>
        <fullName>Approved_Record_Type_Name__c</fullName>
        <label>Approved Record Type Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Record_Type_Name__c</fullName>
        <label>Case Record Type Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unapproved_Record_Type_Name__c</fullName>
        <label>Unapproved Record Type Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Channel</label>
    <nameField>
        <label>Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_ExportPage.cls
@IsTest
public class Test_ExportPage {
    
    @IsTest(seealldata=false)
    public static void testExport() {
        Account a = new Account(name='test');
        insert a;

        Partner__c p = new Partner__c(name='optum',partner_string__c='testp');
        insert p;

        Sales_Channel__c sc = new Sales_Channel__c(Approved_Record_Type_Name__c = 'Engage Approved', Unapproved_Record_Type_Name__c = 'Engage', Case_Record_Type_Name__c = 'Engage', Name='Engage');
         insert sc;

        Milestone1_Project__c imp=new Milestone1_Project__c(Name='imp test', Account__c=a.Id, Partner__c=p.ID);
        insert imp;

        Challenge_Requirement__c tc = new Challenge_Requirement__c(Implementation__c = imp.id, RecordTypeID=label.ChallengeRequirement_TeamRTID);
        insert tc;

        ExportClass exp = new ExportClass(new ApexPages.StandardController(imp));

        exp.export();
        
    }
}