src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Last_Status_Change__c</fullName>
        <description>Stores the last time the status changed -- used by the Case Business Hours Tools package.</description>
        <label>Last Status Change</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/SurveyTaker__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Surveys Taken</relationshipLabel>
        <relationshipName>SurveyTakers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Survey Taken</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surveys Taken</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SurveyTakenTriggerTest.cls
@isTest
public class SurveyTakenTriggerTest {
    public static testMethod void unittest() {
    
      //creating sample data
      Case c = new Case();
        c.Status = 'New_test';
        c.Last_Status_Change__c = System.Now();
        c.Origin = 'Phone';
        c.recordtypeid = label.CC_Default_CASE_RECORDTYPE_ID;
        insert c;
        
        SurveyTaker__c st=new SurveyTaker__c();
        st.case__c=c.Id;
        insert st;
        
        Test.startTest();
        
        SurveyTaker__c st1=new SurveyTaker__c();
        st1.case__c=c.Id;
        insert st1;
        
        Test.stopTest();
        
        }
}