src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Call_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>ID of Call Record from External System.</description>
        <externalId>true</externalId>
        <inlineHelpText>ID of Call Record from External System.</inlineHelpText>
        <label>Call ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Call_Type__c</fullName>
        <label>Call Type</label>
        <picklist>
            <controllingField>Origin</controllingField>
            <picklistValues>
                <fullName>Inbound</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outbound</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/classes/TestTaskTriggerHandler.cls
@istest
public class TestTaskTriggerHandler {
	
	@istest(seealldata=false)
	static void TestTaskTriggerHandler() {
		contact con = new contact(lastname='wayne');
		insert con;

		Case c = new case(subject='batman',Call_Id__c='isbrucewayne',contactid=con.id);
		insert c;

		task t = new task(Five9__Five9SessionId__c='isbrucewayne',activitydate=date.today(),status='Completed',priority='Normal');
		insert t;

		task t1 = [select whatid,whoid from task where id = : t.id];

		system.assert(t1.WhatId == c.id);
		system.assert(t1.WhoId == con.id);
	}

	@istest(seealldata=false)
	static void TestTaskTriggerHandler_noID() {
		contact con = new contact(lastname='wayne');
		insert con;

		Case c = new case(subject='batman',Phone__c='9148333669',contactid=con.id,Call_Type__c = 'Outbound');
		insert c;

		task t = new task(Five9__Five9SessionId__c='isbrucewayne',activitydate=date.today(),status='Completed',priority='Normal',Five9__Five9DNIS__c='9148333669');
		insert t;

		task t1 = [select whatid,whoid from task where id = : t.id];

		system.assert(t1.WhatId == c.id);
		system.assert(t1.WhoId == con.id);
	}
}