src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Go_Live__c</fullName>
        <inlineHelpText>When the client goes live.</inlineHelpText>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Membership_Term__c</fullName>
        <defaultValue>3</defaultValue>
        <inlineHelpText>*In Years* - Default to 3</inlineHelpText>
        <label>Membership Term</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>Engage</fullName>
        <active>true</active>
        <businessProcess>Rally</businessProcess>
        <label>Engage</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Implementation_Fee__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Implementation Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Product_Sub_Type__c</fullName>
        <label>Product Sub-Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Product_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Base</fullName>
                </value>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>Premium</fullName>
                </value>
                <value>
                    <fullName>Tailored Outcome Rewards</fullName>
                </value>
                <value>
                    <fullName>Tailored Activity Rewards</fullName>
                </value>
                <value>
                    <fullName>Pre-Defined Outcomes</fullName>
                </value>
                <value>
                    <fullName>Pre-Defined Activity</fullName>
                </value>
                <value>
                    <fullName>Upsell Feature</fullName>
                </value>
                <value>
                    <fullName>Standard Feature</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>One Time Fee</fullName>
                </value>
                <value>
                    <fullName>Member Portal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Package</fullName>
                </value>
                <value>
                    <fullName>Feature</fullName>
                </value>
                <value>
                    <fullName>Add-On</fullName>
                </value>
                <value>
                    <fullName>Implementation Fee</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/classes/TestProductScheduleHandler.cls
@istest
public class TestProductScheduleHandler {
	
	@istest(seealldata=false)
	static void TestProductScheduleHandler() {
		//Set up test data
		Account a = new Account(Name='Lexcorp');
        insert a;

        RecordType rt = [select id from RecordType where sObjectType='Opportunity' AND Name = 'Engage'];

        Opportunity opp = new Opportunity(accountid=a.id,name='Lexcorp Engage', closeDate=date.today(), stageName='Test', Go_Live__c = date.today(), Membership_Term__c = 3);
        insert opp;

        Product2 packagee = new Product2(Name='Test Product',isActive=true, Product_Type__c ='Package', Product_Sub_Type__c = 'Base');
        insert packagee;

        Id pricebookId = Test.getStandardPricebookId();

        PricebookEntry pbe = new PricebookEntry(Pricebook2Id=pricebookId, Product2Id=packagee.Id, UnitPrice=99, isActive=true);
        insert pbe;

        opportunityLineItem oli1 = new opportunityLineItem(opportunityid = opp.id, Implementation_Fee__c = 7, pricebookentryid = pbe.id, quantity = 1, unitprice = 10);
        insert oli1;

        List<Opportunity_Schedule__c> con = [select id, End_Date__c, (select id, End_Date__c from Product_Schedule__r) from Opportunity_Schedule__c WHERE Opportunity__c = : opp.Id];
        
        system.assertEquals(1, con.size());
        system.assert(!con[0].Product_Schedule__r.isEmpty());

        Date endCheck;

        for(Product_Schedule__c ps : con[0].Product_Schedule__r){
        	if(endCheck == null || endCheck < ps.End_Date__c)
        		endCheck = ps.End_Date__c;
        }

        system.assertEquals(endCheck, con[0].End_Date__c);
	}
}