src/objects/Survey__c.object
<CustomObject>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Survey_Question__c.object
<CustomObject>
    <fields>
        <fullName>NPS__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NPS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>SurveyQuestions</relationshipLabel>
        <relationshipName>SurveyQuestions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Single Select--Vertical</fullName>
                </value>
                <value>
                    <fullName>Single Select--Horizontal</fullName>
                </value>
                <value>
                    <fullName>Multi-Select--Vertical</fullName>
                </value>
                <value>
                    <fullName>Free Text</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Survey Question</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SurveyQuestionResponse__c.object
<CustomObject>
    <fields>
        <fullName>Response__c</fullName>
        <label>Response</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SurveyTaker__c</fullName>
        <label>SurveyTaker</label>
        <referenceTo>SurveyTaker__c</referenceTo>
        <relationshipName>Survey_Question_Answers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Survey_Question__c</fullName>
        <label>Survey Question</label>
        <referenceTo>Survey_Question__c</referenceTo>
        <relationshipName>Survey_Question_Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Text_Response__c</fullName>
        <label>Text Response</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Survey Question Response</label>
    <nameField>
        <displayFormat>Response-{0000000}</displayFormat>
        <label>Response ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Question Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SurveyTaker__c.object
<CustomObject>
    <fields>
        <fullName>Client_ID__c</fullName>
        <label>Client ID</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Community_ID__c</fullName>
        <label>Community ID</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Platform_ID__c</fullName>
        <label>Platform ID</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rally_ID__c</fullName>
        <label>Rally ID</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Survey_Date__c</fullName>
        <label>Survey Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipName>SurveyTakers1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transaction_ID__c</fullName>
        <label>Transaction ID</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Survey Taken</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surveys Taken</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SurveyQuestionResponseService.cls
@RestResource(urlMapping='/createQuestions/*')
global class SurveyQuestionResponseService {

    @HttpPost   
    global static String createQs() {

        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;

        res.statusCode = 200;

        string jresp = req.requestBody.toString();

        SurveyQuestionResponse questionResp = new SurveyQuestionResponse();
        
        try{
            questionResp = SurveyQuestionResponse.parse(jresp);
        }
        catch(exception ex){
            res.statusCode = 400;
            return ex.getMessage();
        }

        system.debug('SURVEY QUESTION RESPONSE POST IS ' + questionResp);

        if(questionResp != null){

            List<SurveyQuestionResponse__c> newResps = new List<SurveyQuestionResponse__c>();

            system.debug(questionResp);

            //Key value set of strings (NPS, text) to their matching question
            Map<String, ID> qMap = new Map<String,ID>();

            //Loop through the questions for this survey ID and map the NPS and Text Question IDs to be assigned below
            for(Survey_Question__c qq : [select id, name, type__c, NPS__c from Survey_Question__c where Survey__c = :questionResp.surveyID]){
                if(qq.NPS__c)
                    qMap.put(Label.SurveyQuestionResponseService_NPSKeyValue,qq.id);
                else if(qq.type__c == 'Free Text')
                    qMap.put(Label.SurveyQuestionResponseService_TextKeyValue, qq.id);
            }

            system.debug('QMAP IS  ' + qMap);

            //If we don't hav at least an NPS and Comments question we call it off
            if(qMap.size() == 2){

                SurveyTaker__c survTaker = new SurveyTaker__c(Rally_ID__c = questionResp.rallyid, Community_ID__c = questionResp.sessionID, Survey__c = questionResp.surveyID, Source__c = questionResp.appID, Platform_ID__c = questionResp.platformID, Version__c = questionResp.appVersion, Transaction_ID__c = questionResp.TransactionID, Client_ID__c = questionResp.clientID);

                try{
                    if(questionResp.surveyDate != null && questionResp.surveyDate != ''){
                        string survDate = questionResp.surveyDate.replace('T', ' ');
                        system.debug(survDate);
                        survDate = survDate.substring(0,survDate.length()-5);
                        system.debug(survDate);
                        Datetime survDT = DateTime.valueOf(survDate);
                        system.debug(survDT);

                        survTaker.Survey_Date__c = survDT;
                    }
                }
                catch(exception ex){
                    try{
                        string survDate = questionResp.surveyDate.replace('T', ' ');
                        system.debug(survDate);
                        survDate = survDate.replace('Z', '');
                        system.debug(survDate);
                        Datetime survDT = DateTime.valueOf(survDate);
                        system.debug(survDT);

                        survTaker.Survey_Date__c = survDT;
                    }
                    catch(exception ex2){
                        List<Utils.ApexError> aes = new List<Utils.ApexError>();
                        Utils.ApexError ae = new Utils.ApexError();

                        String errString = ex2.getMessage();
                        ae.pageOrProcess = 'SurveyQuestionResponseService - Bad Date: ' + questionResp.surveyDate;
                        ae.userId = UserInfo.getUserId();  
                        ae.errorString = errString;
                        ae.timeStamp = date.today();
                        aes.add(ae);

                        Utils.addSingleErrorLog(aes);

                        res.statusCode = 400;
                        return 'INVALID DATE TIME FORMAT';  
                    }
                }
                
                //Key value set of survey question ids to surveyquestionresponse records stored in the system
                Map<id, SurveyQuestionResponse__c> existingQsMap = new Map<id, SurveyQuestionResponse__c>();

                system.debug('TRANSACTION ID IS ' + questionResp.transactionID);

                SurveyTaker__c[] survCheck = [select id, (select id, Response__c, Text_Response__c, Survey_Question__c, Survey_Question__r.NPS__c, Survey_Question__r.type__c from Survey_Question_Answers__r)
                                                        from SurveyTaker__c WHERE (Transaction_ID__c != NULL AND Transaction_ID__c = : questionResp.TransactionID)];

                if(!survCheck.isEmpty()){

                    system.debug('EXISTING RESPONSE IS ' + survCheck);

                    for(SurveyQuestionResponse__c srq : survCheck[0].Survey_Question_Answers__r){
                        existingQsMap.put(srq.Survey_Question__c, srq);
                    }
                }
                else{
                    try{
                        insert survTaker;
                    }
                    catch(DmlException dml){
                        res.statusCode = 400;
                        return dml.getMessage();
                    }
                }

                id surveyTakeID = !survCheck.isEmpty() ? survCheck[0].id : survTaker.id;
                
                for(SurveyQuestionResponse.Questions sv : questionResp.Questions){
                    SurveyQuestionResponse__c svr = new SurveyQuestionResponse__c();

                    if(sv.question_type == Label.SurveyQuestionResponseService_NPSKeyValue){
                        system.debug('NPS QUESTION RESPONSE' + sv.response);

                        if(existingQsMap.get(qMap.get(Label.SurveyQuestionResponseService_NPSKeyValue)) != null){
                           svr = existingQsMap.get(qMap.get(Label.SurveyQuestionResponseService_NPSKeyValue)); 
                        }
                        else{
                            svr.SurveyTaker__c = surveyTakeID;
                            svr.Survey_Question__c = qMap.get(Label.SurveyQuestionResponseService_NPSKeyValue);
                        }

                        svr.Response__c = sv.Response;
                        system.debug('NPS ANSWER IS ' + svr.Response__c);
                        newResps.add(svr);
                    }
                    else if(sv.question_type == Label.SurveyQuestionResponseService_TextKeyValue){
                        system.debug('TEXT QUESTION RESPONSE' + sv.response);

                        if(existingQsMap.get(qMap.get(Label.SurveyQuestionResponseService_TextKeyValue)) != null)
                           svr = existingQsMap.get(qMap.get(Label.SurveyQuestionResponseService_TextKeyValue)); 
                        else{
                            svr.SurveyTaker__c = surveyTakeID;
                            svr.Survey_Question__c = qMap.get(Label.SurveyQuestionResponseService_TextKeyValue);
                        }
                        
                        svr.Text_Response__c = sv.Response;
                        system.debug('TEXT ANSWER IS ' + svr.Text_Response__c);
                        newResps.add(svr);
                    }
                }

                if(!newResps.isEmpty()){
                    try{
                        upsert newResps;
                        res.statusCode = 201;
                        return 'Success';
                    }
                    catch(DmlException dml){
                        res.statusCode = 400;
                        return dml.getMessage();
                    }
                }
                else{
                    res.statusCode = 201;
                    return 'Success - No Responses';
                }
            }
            else{
                res.statusCode = 400;
                return 'Incorrect Survey ID/Post Payload - Unable to find survey configuration.';
            }
        }
        else{
            res.statusCode = 400;
            return Label.SurveyQuestionResponseService_NoPostBody;
        }
    }
}