src/objects/Survey__c.object
<CustomObject>
    <fields>
        <fullName>Submit_Response__c</fullName>
        <description>Message to be displayed to the user when the Survey has been submitted</description>
        <inlineHelpText>Message to be displayed to the user when the Survey has been submitted</inlineHelpText>
        <label>Submit Response</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Survey_Question__c.object
<CustomObject>
    <fields>
        <fullName>Choices_New__c</fullName>
        <label>Choices New</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>NPS__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NPS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderNumber__c</fullName>
        <description>Field to specify in which position the question is in the survey.</description>
        <inlineHelpText>Enter the position of the question within the survey here.</inlineHelpText>
        <label>OrderNumber</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question_New__c</fullName>
        <label>Question New</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Required__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is the question required?</description>
        <inlineHelpText>Check this box if you want the taker to be required to take the question.</inlineHelpText>
        <label>Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>SurveyQuestions</relationshipLabel>
        <relationshipName>SurveyQuestions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Single Select--Vertical</fullName>
                </value>
                <value>
                    <fullName>Single Select--Horizontal</fullName>
                </value>
                <value>
                    <fullName>Multi-Select--Vertical</fullName>
                </value>
                <value>
                    <fullName>Free Text</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Survey Question</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SurveyQuestionResponse__c.object
<CustomObject>
    <fields>
        <fullName>Response__c</fullName>
        <label>Response</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SurveyTaker__c</fullName>
        <label>SurveyTaker</label>
        <referenceTo>SurveyTaker__c</referenceTo>
        <relationshipName>Survey_Question_Answers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Survey_Question__c</fullName>
        <label>Survey Question</label>
        <referenceTo>Survey_Question__c</referenceTo>
        <relationshipName>Survey_Question_Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Survey Question Response</label>
    <nameField>
        <displayFormat>Response-{0000000}</displayFormat>
        <label>Response ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Question Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SurveyTaker__c.object
<CustomObject>
    <fields>
        <fullName>Survey_Date__c</fullName>
        <label>Survey Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipName>SurveyTakers1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transaction_ID__c</fullName>
        <label>Transaction ID</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Survey Taken</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surveys Taken</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_SurveyQuestionResponseService.cls
@istest(seealldata=false)
public class Test_SurveyQuestionResponseService {
	
	@istest(seealldata=false)
	static void testCreate(){

		Survey__c s = new Survey__c();
	    s.Name = 'Testing Survey';
	    s.Submit_Response__c = 'empty'; 
	    insert s;

	    Survey_Question__c q = new Survey_Question__c();
	    q.Name = 'Testing Question';
	    q.Survey__c = s.id;
	    q.Type__c = 'Free Text';
	    q.Choices_New__c = '';
	    q.Question_New__c = 'Text q';
	    q.OrderNumber__c = 0;
	    q.Required__c = true;
	    insert q;

	    Survey_Question__c q1 = new Survey_Question__c();
	    q1.Name = 'Testing Question';
	    q1.Survey__c = s.id;
	    q1.Type__c = 'Single Select--Horizontal';
	    q1.Choices_New__c = 'one\ntwo\nthree\n';
	    q1.NPS__c = true;
	    q1.Question_New__c = 'NPS';
	    q1.OrderNumber__c = 1;
	    q1.Required__c = true;
	    insert q1;
		
		//uid = ApexPages.currentPage().getParameters().get('id');
		RestRequest req = new RestRequest(); 
	    RestResponse res = new RestResponse();

	    // pass the req and resp objects to the method     
	    req.requestURI = Label.Test_SurveyQuestionResponseService_DomainAddy;  
	    req.httpMethod = 'POST';
	    req.requestBody = blob.valueOf('{ "rallyID" : "someID", "sessionID" : "someSessID", "clientID" : "someCID", "payerID" : "somepID", "surveyID" : "'+s.id+'", "sourceID" : "Mobile", "transactionID" : "someID1234", "Questions" : [{"question_type" : "NPS", "response" : "10"}, { "question_type" : "text", "response" : "Some comment"}]}');

	    RestContext.request = req;
	    RestContext.response = res;

	    string resulty = SurveyQuestionResponseService.createQs();

		System.assertEquals('Success',resulty);

		SurveyTaker__c st = [select id, Transaction_ID__c from SurveyTaker__c where Survey__c = :s.id];
		system.assertEquals('someID1234', st.Transaction_ID__c);

		RestRequest req1 = new RestRequest(); 
	    RestResponse res1 = new RestResponse();

	    // pass the req and resp objects to the method     
	    req1.requestURI = Label.Test_SurveyQuestionResponseService_DomainAddy;  
	    req1.httpMethod = 'POST';
	    req1.requestBody = blob.valueOf('{ "rallyID" : "someID", "sessionID" : "someSessID", "clientID" : "someCID", "payerID" : "somepID", "surveyID" : "'+s.id+'", "sourceID" : "Mobile", "transactionID" : "someID1234", "Questions" : [{"question_type" : "NPS", "response" : "9"}, { "question_type" : "text", "response" : "Some comment updated"}]}');

	    RestContext.request = req1;
	    RestContext.response = res1;

		string resulty2 = SurveyQuestionResponseService.createQs();

		System.assertEquals('Success',resulty2);

		SurveyQuestionResponse__c resp = [select id,response__c from SurveyQuestionResponse__c where SurveyTaker__r.Survey__c = :s.id AND Survey_Question__r.NPS__c = true];
		system.assertEquals('9', resp.response__c);
		
	}

	@istest(seealldata=false)
	static void testCreateDate(){

		Survey__c s = new Survey__c();
	    s.Name = 'Testing Survey';
	    s.Submit_Response__c = 'empty'; 
	    insert s;

	    Survey_Question__c q = new Survey_Question__c();
	    q.Name = 'Testing Question';
	    q.Survey__c = s.id;
	    q.Type__c = 'Free Text';
	    q.Choices_New__c = '';
	    q.Question_New__c = 'Text q';
	    q.OrderNumber__c = 0;
	    q.Required__c = true;
	    insert q;

	    Survey_Question__c q1 = new Survey_Question__c();
	    q1.Name = 'Testing Question';
	    q1.Survey__c = s.id;
	    q1.Type__c = 'Single Select--Horizontal';
	    q1.Choices_New__c = 'one\ntwo\nthree\n';
	    q1.NPS__c = true;
	    q1.Question_New__c = 'NPS';
	    q1.OrderNumber__c = 1;
	    q1.Required__c = true;
	    insert q1;
		
		//uid = ApexPages.currentPage().getParameters().get('id');
		RestRequest req = new RestRequest(); 
	    RestResponse res = new RestResponse();

	    // pass the req and resp objects to the method     
	    req.requestURI = Label.Test_SurveyQuestionResponseService_DomainAddy;  
	    req.httpMethod = 'POST';
	    req.requestBody = blob.valueOf('{ "rallyID" : "someID", "sessionID" : "someSessID", "surveyDate" : "2017-03-30T18:55:49.662Z", "clientID" : "someCID", "payerID" : "somepID", "surveyID" : "'+s.id+'", "sourceID" : "Mobile", "transactionID" : "someID1234", "Questions" : [{"question_type" : "NPS", "response" : "10"}, { "question_type" : "text", "response" : "Some comment"}]}');

	    RestContext.request = req;
	    RestContext.response = res;

	    string resulty = SurveyQuestionResponseService.createQs();

		System.assertEquals('Success',resulty);

		SurveyTaker__c st = [select id, Transaction_ID__c, Survey_Date__c from SurveyTaker__c where Survey__c = :s.id];
		system.assertEquals('someID1234', st.Transaction_ID__c);
	}
}